config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'partner_relations/create'

  get 'partner_relations/destroy'

  resources :research_partners
  resources :news
  get 'services/new'

  get 'services/show'

  get 'services/index'

  get 'services/edit'

  get 'services/creat'

  get 'services/destroy'

  get 'services/update'

  get 'facility_contact/create'

  get 'facility_contact/destroy'

  get 'static_pages/home'

  get 'publish_user_relationships/create'

  get 'publish_user_relationships/destroy'

  get 'publish_relationships/new'

  get 'publish_relationships/show'

  get 'publish_relationships/index'

  get 'publish_relationships/edit'

  get 'publications/new'

  get 'publications/show'

  get 'publications/index' 

  get 'publications/edit'

  get 'galleries/show'

  get 'galleries/new'

  get 'galleries/index'

  get 'galleries/edit'

  get 'sessions/new'

  get 'authors/new'

  get 'authors/index'

  get 'authors/show'

  get '/signup', to: 'users#new'

  get '/newproject', to: 'projects#new'
  
  get '/newfacility', to: 'facilities#new'

  get '/home', to: 'static_pages#home'
  
  get '/teaching', to: 'static_pages#research'

  get '/ensc283', to: 'static_pages#ENSC283'
  
  get '/ensc321', to: 'static_pages#ensc321'

  get '/ensc423', to: 'static_pages#ensc423'

  get '/partners', to: 'research_partners#index'
  
  get '/research', to: 'projects#index'

  get '/services', to: 'services#index'

  get '/location', to: 'static_pages#service'

  get '/about', to:'static_pages#aboutus'

  get '/login',   to: 'sessions#new'
  
  post  '/login',   to: 'sessions#create'
  
  delete '/logout',  to: 'sessions#destroy'

  root 'static_pages#home'
  
  resources :static_pages
  resources :research_partners
  resources :partner_relations
  resources :publish_user_relationships
  resources :publish_relationships
  resources :publications
  resources :users
  resources :services             
  resources :projects             
  resources :facilities
  resources :galleries
  resources :facility_contacts,      only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :users do
    member do
      get :articles
    end
  end
  
  resources :projects do
    member do
      get :authors
    end
  end
  

end

app/models/publication.rb
class Publication < ApplicationRecord
  has_many :publish_user_relationships, foreign_key: "publication_id",
                                  dependent: :destroy
  has_many :users ,through: :publish_user_relationships
  
  has_many :publish_relationships, foreign_key: "publication_id",
                                  dependent: :destroy
  has_many :projects ,through: :publish_relationships
  
  has_attached_file :file,
    default_url: lambda { |image| ActionController::Base.helpers.asset_path('missing.png') }

  validates_attachment :file,
  :content_type => { :content_type => 'application/pdf' },
  :size => { :in => 0..100.megabytes }

  def add(user)
    publish_user_relationships.create(user_id: user.id)
  end

  def quit(user)
    publish_user_relationships.find_by(user_id: user.id).destroy
  end

  def author?(user)
    users.include?(user)
  end
  
  def relate(project)
    publish_relationships.create(project_id: project.id)
  end

  def disrelate(project)
    publish_relationships.find_by(project_id: project.id).destroy
  end

  def relate?(project)
    projects.include?(project)
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  
    before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]

  def new
    @publication = Publication.new
    @users = User.all
  end

  def show
    @publication = Publication.find(params[:id])
  end

  def index
    @publications = Publication.all
    
    @array = []
    @publications.each do |d|
      @array.push(d.time)
    end  
    @pub_year = @array.uniq.sort{|x,y| y <=> x }
    @large_element = @pub_year.first
  end


  def create
    @publication = Publication.new(publication_params)
    if @publication.save
      redirect_to new_publication_path
    else
      render 'new'
    end
  end
  
  def edit
    
    @publication = Publication.find(params[:id])
    @users = User.all
  end
  
  private

    def publication_params
      params.require(:publication).permit(:title, :descryption, :file, :users, :time )
    end
    
  
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_add.html.erb
  <%= form_for(publication.publish_user_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :user_id, user.id %></div>
    <div><%= hidden_field_tag :publication_id, publication.id %></div>
    <%= f.submit "Add to author", class: "btn btn-primary" %>
  <% end %>

app/views/publications/_author_form.html.erb
<ul>

          <div class = "participate_list">
          <% @users = @users - @publication.users%>
          <% @users.each do |user| %>
              <div class = "item">
              <div class = "card_pic card_pic2 col-md-4">
                <%= link_to image_tag(user.image.url()), user.image.url %>
               </div>                
                <%= link_to user.name, user %>
                <% if user.participate?(@publication) %>
                <% else %>
                  <%= render partial: "publications/add", locals: { user: user, publication: @publication} %> 
                <% end %> 
              </div>
          <% end %>
        </div>
        
        
        <div class = "participate_list">
          <% @publication.users.each do |user| %>
              <div class = "item">
              <div class = "card_pic card_pic2 col-md-4">
                <%= link_to image_tag(user.image.url()), user.image.url %>
               </div>                
                <%= link_to user.name, user %>
                <% if user.author?(@publication) %>
                  <%= render partial: "publications/quit", locals: { user: user, publication: @publication} %> 
                <% end %> 
              </div>
          <% end %>
        </div>
          
          
          

</ul>

app/views/publications/_quit.html.erb
<%= form_for(publication.publish_user_relationships.find_by(publication_id: publication.id),
               html: { method: :delete }, remote: true) do |f| %>
    <div><%= hidden_field_tag :user_id, user.id %></div>
    <div><%= hidden_field_tag :publication_id, publication.id %></div>
    <%= f.submit "Quit", class: "btn btn-danger" %>
<% end %>                  

app/views/publications/edit.html.erb
<div>
  <div id = "edit_form"><%= render partial: 'author_form'%></div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_for(@publication) do |f| %>

      <%= f.label :Title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :descryption %>
      <%= f.text_area :descryption, class: 'form-control' %>

      <%= f.label :year %>
      <%= f.number_field :time %>
      
      <%= f.file_field :file %>

      
      <%= f.submit "Upload my publication", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>

app/views/publications/index.html.erb
<% provide(:title, 'All Publications') %>

<div class = "side-nav col-md-2">
  <p style = "font-size:2em; "><strong>Quick Index</strong></p>
  <% @pub_year.each do |array| %>
    <div class = "side-nav-list">
      <%= link_to array, publications_path(:anchor => "publication-#{array}") %>
    </div>
  <% end %>

</div>

<div class = "term_detail col-md-10 col-md-offset-2">
  <div class = "detail-page-title">Publications</div>

  <div class = "pub_list">
  <% @pub_year.each do |array| %> 
    <div class = "pub_year container col-md-12">
      <div class = "anchor_blank" id="publication-<%=array%>"></div>
        <p><strong><%= array %></strong></p>
        <button id = "#pub_year-<%=array%>" type="button" class="btn btn-custom5" data-toggle="collapse" onclick="switchtext(id)" data-target="#pub_year-<%=array%>"><%= array == @large_element ? "Collapse ↑" : "Expand ↓" %></button>
          <div class="publications col-md-12">
            <div id="pub_year-<%=array%>" class="col-md-12 <%= array == @large_element ? 'collapse in' : 'collapse' %>">
            <% @publications.each do |publication| %>
              <% if publication.time == array %>
                <div class = "publication_brief">
                  <% if current_user %>
                    <p><%= link_to publication.title, edit_publication_path(publication) %></p>
                  <% else %>
                    <p><%= link_to publication.title, publication_path(publication) %></p>
                  <% end %>

                  <%= truncate(publication.descryption, :length => 250) %>
                </div>
              <% end %>  
            <% end %>
           </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<script>
  function switchtext(a) {
    x = document.getElementById(a);
    if (x.innerHTML == "Expand ↓"){
      x.innerHTML = ("Collapse ↑");
    }
    else {
     x.innerHTML = ("Expand ↓");
    }
  }

</script>

app/views/publications/new.html.erb
<% provide(:title, 'New Publication') %>
<h1>New Publication</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_for(@publication) do |f| %>

      <%= f.label :Title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :descryption %>
      <%= f.text_area :descryption, class: 'form-control' %>

      <%= f.label :year %>
      <%= f.number_field :time %>
      
      <%= f.file_field :file %>

      
      <%= f.submit "Upload my publication", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/publications/show.html.erb
<div class = "container-fluid project-detail" id="project-<%= @publication.id %>">
  <div class = "col-md-10 col-md-offset-1">
    <span class="pub-title col-md-12"><%= @publication.title%></span>
    <%= link_to "download this file", @publication.file.url(), :class => "download-text"%>
    <span class="project-description col-md-12"><%= @publication.descryption  %></span>
        <span class="user col-md-10 topic col-xs-12">Authors:</span>
        <div class = "users-icon container">
          <% @publication.users.each do |user| %>
              <div class = "users-selection col-md-2 col-xs-6">
                <div class = " container card_pic6 col-md-6 col-xs-5">
                  <%= link_to image_tag(user.image.url()), user %>
                 </div> 
                 <div class = " container card_pic6 col-md-6 col-xs-5">
                   <%= link_to user.name, user %>
                   <%= link_to user.last_name, user %>
                 </div> 

              </div>
          <% end %>
      
    </div>
  </div>
</div>