config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'partner_relations/create'

  get 'partner_relations/destroy'

  resources :research_partners
  resources :news
  get 'services/new'

  get 'services/show'

  get 'services/index'

  get 'services/edit'

  get 'services/creat'

  get 'services/destroy'

  get 'services/update'

  get 'facility_contact/create'

  get 'facility_contact/destroy'

  get 'static_pages/home'

  get 'publish_user_relationships/create'

  get 'publish_user_relationships/destroy'

  get 'publish_relationships/new'

  get 'publish_relationships/show'

  get 'publish_relationships/index'

  get 'publish_relationships/edit'

  get 'publications/new'

  get 'publications/show'

  get 'publications/index' 

  get 'publications/edit'

  get 'galleries/show'

  get 'galleries/new'

  get 'galleries/index'

  get 'galleries/edit'

  get 'sessions/new'

  get 'authors/new'

  get 'authors/index'

  get 'authors/show'

  get '/signup', to: 'users#new'

  get '/newproject', to: 'projects#new'
  
  get '/newfacility', to: 'facilities#new'

  get '/home', to: 'static_pages#home'
  
  get '/teaching', to: 'static_pages#research'

  get '/ensc283', to: 'static_pages#ENSC283'
  
  get '/ensc321', to: 'static_pages#ensc321'

  get '/ensc423', to: 'static_pages#ensc423'

  get '/partners', to: 'research_partners#index'
  
  get '/research', to: 'projects#index'

  get '/services', to: 'services#index'

  get '/location', to: 'static_pages#service'

  get '/about', to:'static_pages#aboutus'

  get '/login',   to: 'sessions#new'
  
  post  '/login',   to: 'sessions#create'
  
  delete '/logout',  to: 'sessions#destroy'

  root 'static_pages#home'
  
  resources :static_pages
  resources :research_partners
  resources :partner_relations
  resources :publish_user_relationships
  resources :publish_relationships
  resources :publications
  resources :users
  resources :services             
  resources :projects             
  resources :facilities
  resources :galleries
  resources :facility_contacts,      only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :users do
    member do
      get :articles
    end
  end
  
  resources :projects do
    member do
      get :authors
    end
  end
  

end

app/models/news.rb
class News < ApplicationRecord
    has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }

  validates_attachment :image, :presence => true,
  :content_type => { content_type: ["image/jpg","image/jpeg","image/png","image/gif"] },
  :size => { :in => 0..100.megabytes }

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
    @news_team = News.where("categoty = 2")
    @array = []
    @news.each do |d|
      @array.push(d.year)
    @cate_array = @array.uniq.sort{|x,y| y <=> x }
    @large_element = @cate_array.first
    @research_partners = ResearchPartner.all
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :description, :image, :categoty, :year, :month)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@news) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.file_field :image %>

      <%= f.label :category %>
      <%= f.select(:categoty, options_for_select([['Home Page', 1], ['Team Page', 2], ['None', 3]])) %>
      
      <%= f.label :year %>
      <%= f.number_field :year, class: 'form-control' %>
      
      <%= f.label :month %>
      <%= f.text_field :month, class: 'form-control' %>

      <%= f.submit "Create News", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>
<%= link_to "delete", @news, method: :delete,
                                        data: { confirm: "You sure?" } %>
<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>
<script>
  function switchtext(a) {
    x = document.getElementById(a);
    if (x.innerHTML == "Expand"){
      x.innerHTML = ("Collapse");
    }
    else {
     x.innerHTML = ("Expand");
    }
  }

</script>


    <span class = "detail-page-title col-md-12">News</span>

<div class = "information col-md-10 col-md-offset-1">
  <% if logged_in? %>
    <%= link_to 'New News', new_news_path, :class => "btn btn-success col-md-12" %>
  <% end %>
  <% if @cate_array %>
    <% @cate_array.each do |array| %>
      <div class = "block">
          <p><strong><%= array %></strong></p>
          <button id = "#news-<%=array%>" type="button" class="btn btn-custom5" data-toggle="collapse" onclick="switchtext(id)" data-target="#news-<%=array%>"><%= array == @large_element ? "Collapse" : "Expand" %></button>
            <div id="news-<%=array%>" class="news_index col-md-12 <%= array == @large_element ? 'collapse in' : 'collapse' %>">
              <% @news.each do |news| %>
                <% if news.year == array %>
                  <div class = "news_list_brief container" id="news-<%= news.id %>">
                    <div class = "col-md-2">
                      <%= link_to image_tag(news.image.url()), news%>
                    </div>
                    <strong><%= link_to news.title, news, {:class=>"news-title"}%></strong><br>
                    <span class = "col-xs-12 col-md-9"><%= truncate(news.description, :length => 250, :class=>"news-title") %></span>
                    <span class = "col-md-10"><%= link_to "View more", news%></span>
                  </div>
                <% end %>
              <% end %>
            </div>
            </div>
      <% end %>
    <% end %>


  <br>


</div>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<div class = "col-md-8 col-md-offset-2 project-detail">
  
  <span class="title col-md-12"><%= @news.title%></span>

  <span class="user col-md-12">
     Time: <%= @news.month %>, <%= @news.year %>.</span>

  <div class = "project-image">
    <%= link_to image_tag(@news.image.url()), @news.image.url %>
  </div>

  <span class="col-md-8 col-md-offset-2" style = "margin-top:1em;"><%= @news.description%></span>

  <div class="margin-bottom container col-md-12"></div>
  

</div>

<% if logged_in? %>
  <%= link_to 'Edit', edit_news_path(@news) %> |
  <%= link_to 'Back', news_index_path %>
<% end %>