config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'partner_relations/create'

  get 'partner_relations/destroy'

  resources :research_partners
  resources :news
  get 'services/new'

  get 'services/show'

  get 'services/index'

  get 'services/edit'

  get 'services/creat'

  get 'services/destroy'

  get 'services/update'

  get 'facility_contact/create'

  get 'facility_contact/destroy'

  get 'static_pages/home'

  get 'publish_user_relationships/create'

  get 'publish_user_relationships/destroy'

  get 'publish_relationships/new'

  get 'publish_relationships/show'

  get 'publish_relationships/index'

  get 'publish_relationships/edit'

  get 'publications/new'

  get 'publications/show'

  get 'publications/index' 

  get 'publications/edit'

  get 'galleries/show'

  get 'galleries/new'

  get 'galleries/index'

  get 'galleries/edit'

  get 'sessions/new'

  get 'authors/new'

  get 'authors/index'

  get 'authors/show'

  get '/signup', to: 'users#new'

  get '/newproject', to: 'projects#new'
  
  get '/newfacility', to: 'facilities#new'

  get '/home', to: 'static_pages#home'
  
  get '/teaching', to: 'static_pages#research'

  get '/ensc283', to: 'static_pages#ENSC283'
  
  get '/ensc321', to: 'static_pages#ensc321'

  get '/ensc423', to: 'static_pages#ensc423'

  get '/partners', to: 'research_partners#index'
  
  get '/research', to: 'projects#index'

  get '/services', to: 'services#index'

  get '/location', to: 'static_pages#service'

  get '/about', to:'static_pages#aboutus'

  get '/login',   to: 'sessions#new'
  
  post  '/login',   to: 'sessions#create'
  
  delete '/logout',  to: 'sessions#destroy'

  root 'static_pages#home'
  
  resources :static_pages
  resources :research_partners
  resources :partner_relations
  resources :publish_user_relationships
  resources :publish_relationships
  resources :publications
  resources :users
  resources :services             
  resources :projects             
  resources :facilities
  resources :galleries
  resources :facility_contacts,      only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :users do
    member do
      get :articles
    end
  end
  
  resources :projects do
    member do
      get :authors
    end
  end
  

end

app/models/research_partner.rb
class ResearchPartner < ApplicationRecord
   has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }

  validates_attachment :image, :presence => true,
  :content_type => { content_type: ["image/jpg","image/jpeg","image/png","image/gif"] },
  :size => { :in => 0..100.megabytes }
end

app/controllers/research_partners_controller.rb
class ResearchPartnersController < ApplicationController
  before_action :set_research_partner, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]

  # GET /research_partners
  # GET /research_partners.json
  def index
    @research_partners = ResearchPartner.all
  end

  # GET /research_partners/1
  # GET /research_partners/1.json
  def show
  end

  # GET /research_partners/new
  def new
    @research_partner = ResearchPartner.new
  end

  # GET /research_partners/1/edit
  def edit
  end

  # POST /research_partners
  # POST /research_partners.json
  def create
    @research_partner = ResearchPartner.new(research_partner_params)

    respond_to do |format|
      if @research_partner.save
        format.html { redirect_to @research_partner, notice: 'Research partner was successfully created.' }
        format.json { render :show, status: :created, location: @research_partner }
      else
        format.html { render :new }
        format.json { render json: @research_partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /research_partners/1
  # PATCH/PUT /research_partners/1.json
  def update
    respond_to do |format|
      if @research_partner.update(research_partner_params)
        format.html { redirect_to @research_partner, notice: 'Research partner was successfully updated.' }
        format.json { render :show, status: :ok, location: @research_partner }
      else
        format.html { render :edit }
        format.json { render json: @research_partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /research_partners/1
  # DELETE /research_partners/1.json
  def destroy
    @research_partner.destroy
    respond_to do |format|
      format.html { redirect_to research_partners_url, notice: 'Research partner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_research_partner
      @research_partner = ResearchPartner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def research_partner_params
      params.require(:research_partner).permit(:title, :description, :image)
    end
end

app/helpers/research_partners_helper.rb
module ResearchPartnersHelper
end

app/views/research_partners/_form.html.erb
<div class = "col-md-12">
  <div class = "col-md-10 col-md-offset-1">
    <%= simple_form_for(@research_partner) do |f| %>
      <%= f.error_notification %>
    
        <%= f.label :Name %>
        <%= f.text_field :title, class: 'form-control' %>
    
        <%= f.label :Link %>
        <%= f.text_field :description, class: 'form-control' %>
        
        <%= f.file_field :image %>
    
      <div class="form-actions">
        <%= f.button :submit, :class => "btn btn-success" %>
      </div>
    <% end %>
  </div>                    
</div>

app/views/research_partners/edit.html.erb
<h1>Editing Research Partner</h1>

<%= render 'form', research_partner: @research_partner %>

<%= link_to 'Show', @research_partner %> |
<%= link_to 'Back', research_partners_path %>

app/views/research_partners/index.html.erb
  <tbody>
    <div class = "info-partner col-md-10 col-md-offset-1">
            <p class = "detail-page-title"><strong>Research Partners</strong></p>
    <% if current_user %>
      <%= link_to 'New Research Partner', new_research_partner_path, :class => "btn btn-success"%>
    <% end %>
      <div class = "partner-list container">
        <% @research_partners.each do |research_partner| %>
          <div class = "col-md-3 col-sm-3 col-xs-12  research_partner_list">
            <div class = "block-p">
              <div class = "col-md-12 col-sm-12 col-xs-12 card_pic3 card_pic4">
                <td><%= link_to image_tag(research_partner.image.url()), research_partner.description%></td>
              </div>
              <div class = "col-md-12 col-sm-12 col-xs-12">
                <td><%= research_partner.title %></td>
              </div>
              <% if logged_in? %>
                <td><%= link_to 'Edit', edit_research_partner_path(research_partner) %></td>
                <td><%= link_to 'Destroy', research_partner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>  
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </tbody>

app/views/research_partners/new.html.erb
<h1>New Research Partner</h1>

<%= render 'form', research_partner: @research_partner %>

<%= link_to 'Back', research_partners_path %>

app/views/research_partners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @research_partner.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @research_partner.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @research_partner.image %>
</p>
<% if logged_in? %>
<%= link_to 'Edit', edit_research_partner_path(@research_partner) %> |
<%= link_to 'Back', research_partners_path %>
<% end %>